# Generated by Django 4.1.2 on 2022-10-29 14:22

import django.core.validators
from django.db import migrations, models
import exam_prep.web.validators


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.MinLengthValidator(2), exam_prep.web.validators.validate_only_alphanumeric]),
        ),
    ]
